version: "3.7"

services:
  db:
    build: .docker/db
    container_name: rentx_db
    tty: true
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
